on: pull_request

permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Delta TypeScript Graph
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ysk8hori/delta-typescript-graph-action@v1.0.5
        with:
          tsconfig-root: './my-app'
          debug: true
